export const travelTemplate = {
  temname: "Travel Template",
  previewContent: [
    {
      type: "banner",
      src: "https://ik.imagekit.io/w1dqqzgef/flat-landing-page-template-travel-agency.png",
      style: {
        width: "100%",
        height: "auto",
        borderRadius: "0px",
        textAlign: "center",
      },
    },
    {
      type: "head",
      content: "Sunset Holidays – Your Journey Begins Here",
      style: {
        fontSize: "26px",
        color: "#b9375e",
        textAlign: "center",
        padding: "12px 0",
        fontWeight: "bold",
      },
    },
  {
  type: "para",
  content: "The world is waiting — beaches, mountains, ancient cities, and vibrant cultures. With Sunset Holidays, every journey is crafted to perfection. All-inclusive stays, flight deals, and local guides ensure your trip is unforgettable. Let the sunset guide your next adventure.",
  style: {
    fontSize: "15px",
    borderRadius: "0px",
    textAlign: "center",
    color: "#3d3d3d",
    backgroundColor: "#fff0e1",
    padding: "15px",
  },
},
    {
      type: "multipleimage",
      src1: "https://ik.imagekit.io/w1dqqzgef/2633.jpg?updatedAt=1753427879587",
      src2: "https://ik.imagekit.io/w1dqqzgef/2633.jpg?updatedAt=1753427879587",
      style: {
        width: "100%",
        height: "auto",
        borderRadius: "10px",
        textAlign: "center",
      },
    },
    {
      type: "imagewithtext",
      src1: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2073&q=80",
      content1: "Experience the magic of Santorini with its iconic blue-domed churches and breathtaking sunsets. Wander through charming villages, savor authentic Greek cuisine, and create memories that last a lifetime in this Mediterranean paradise.",
      style1: {
        borderRadius: "10px",
        backgroundColor: "#fff0e1",
        color: "#333",
        padding: "20px",
        fontSize: "16px",
        lineHeight: "1.6",
      }
    },
    {
      type: "textwithimage",
      src2: "https://images.unsplash.com/photo-1516426122078-c23e76319801?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2068&q=80",
      content2: "Embark on the ultimate African safari adventure where wildlife roams free and nature reigns supreme. Witness the Big Five in their natural habitat, stay in luxury eco-lodges, and experience the raw beauty of the African wilderness under starlit skies.",
      style: {
        backgroundColor: "#fff0e1",
        color: "#333",
        borderRadius: "10px",
        padding: "20px",
        fontSize: "16px",
        lineHeight: "1.6",
      },
    },
    {
      type: "image",
      src: "https://ik.imagekit.io/w1dqqzgef/travel-images.jpg",
      url: "https://sunsetholidays.com/family-trips",
      style: {
        width: "100%",
        height: "auto",
        textAlign: "center",
        margin: "10px auto",
        borderRadius: "10px",
      },
    },
    {
      type: "head",
      content: "Top Trending Destinations ✈️",
      style: {
        fontSize: "24px",
        color: "#b9375e",
        textAlign: "center",
        fontWeight: "bold",
        paddingTop: "10px",
      },
    },
    {
      type: "multi-image-card",
      src1: "https://ik.imagekit.io/w1dqqzgef/trending%20destination.jpg",
      src2: "https://ik.imagekit.io/w1dqqzgef/trending%20destination.jpg",
      title1: "Thailand Adventure",
      title2: "Bali Beach Bliss",
      originalPrice1: "₹60,000",
      offerPrice1: "₹39,999",
      originalPrice2: "₹70,000",
      offerPrice2: "₹45,000",
      content1: "Book Now",
      content2: "Book Now",
      link1: "https://sunsetholidays.com/thailand",
      link2: "https://sunsetholidays.com/bali",
      buttonStyle1: {
        textAlign: "center",
        padding: "12px 15px",
        backgroundColor: "#b9375e",
        color: "#ffffff",
        width: "80%",
        borderRadius: "12px",
        fontWeight: "bold",
        fontSize: "14px",
      },
      buttonStyle2: {
        textAlign: "center",
        padding: "12px 15px",
        backgroundColor: "#b9375e",
        color: "#ffffff",
        width: "80%",
        borderRadius: "12px",
        fontWeight: "bold",
        fontSize: "14px",
      },
      style: {
        width: "100%",
        height: "auto",
        textAlign: "center",
        borderRadius: "0px",
      },
    },
    {
      type: "multi-image-card",
      src1: "https://ik.imagekit.io/w1dqqzgef/playa-y-acantilados-en-bali-indonesia-1.jpg",
      src2: "https://ik.imagekit.io/w1dqqzgef/playa-y-acantilados-en-bali-indonesia-1.jpg",
      title1: "Thailand Adventure",
      title2: "Bali Beach Bliss",
      originalPrice1: "₹60,000",
      offerPrice1: "₹39,999",
      originalPrice2: "₹70,000",
      offerPrice2: "₹45,000",
      content1: "Book Now",
      content2: "Book Now",
      link1: "https://sunsetholidays.com/thailand",
      link2: "https://sunsetholidays.com/bali",
      buttonStyle1: {
        textAlign: "center",
        padding: "12px 15px",
        backgroundColor: "#b9375e",
        color: "#ffffff",
        width: "80%",
        borderRadius: "12px",
        fontWeight: "bold",
        fontSize: "14px",
      },
      buttonStyle2: {
        textAlign: "center",
        padding: "12px 15px",
        backgroundColor: "#b9375e",
        color: "#ffffff",
        width: "80%",
        borderRadius: "12px",
        fontWeight: "bold",
        fontSize: "14px",
      },
      style: {
        width: "100%",
        height: "auto",
        textAlign: "center",
        borderRadius: "0px",
      },
    },
    {
      type: "head",
      content: "Limited-Time Offer 🎁",
      style: {
        fontSize: "22px",
        textAlign: "center",
        color: "#cc3300",
        fontWeight: "bold",
      },
    },{
  type: "para",
  content: "Book before July 31st and get up to 40% off + a free travel kit with every booking!",
  style: {
    fontSize: "15px",
    borderRadius: "0px",
    textAlign: "center",
    color: "#3d3d3d",
    backgroundColor: "#fff0e1",
    padding: "15px",
  },
},
    
    {
      type: "button",
      content: "Explore All Packages",
      buttonType: "link",
      link: "https://sunsetholidays.com/packages",
      style: {
        textAlign: "center",
        padding: "12px 25px",
        backgroundColor: "#b9375e",
        color: "#ffffff",
        width: "auto",
        fontWeight: "bold",
        fontSize: "15px",
        borderRadius: "10px",
        margin: "10px auto",
      },
    },
    {
      type: "icons",
      iconsrc1: "https://res.cloudinary.com/diytyjnla/image/upload/v1748582430/facebook_crpxwo.png",
      style1: { width: "30px", height: "30px" },
      links1: "https://facebook.com/sunsetholidays",

      iconsrc2: "https://res.cloudinary.com/diytyjnla/image/upload/v1748582461/twitter_g6czs3.png",
      style2: { width: "30px", height: "30px" },
      links2: "https://twitter.com/sunsetholidays",

      iconsrc3: "https://res.cloudinary.com/diytyjnla/image/upload/v1748582448/Instagram_fj4sqm.png",
      style3: { width: "30px", height: "30px" },
      links3: "https://instagram.com/sunsetholidays",

      iconsrc4: "https://res.cloudinary.com/diytyjnla/image/upload/v1748582471/youtube_egb71v.png",
      style4: { width: "30px", height: "30px" },
      links4: "https://youtube.com/sunsetholidays",

      ContentStyle: {
        width: "100%",
        backgroundColor: "#fff0e5",
        textAlign: "center",
      },
    },
   {
  type: "para",
  content: "© 2025 Your Company. All rights reserved. You received this email because you're subscribed to travel updates.",
  style: {
    fontSize: "14px",
    borderRadius: "0px",
    textAlign: "center",
    color: "#444",
    backgroundColor: "#ffffff",
    padding: "10px",
  },
},
  ],
  bgColor: "#ffffff",
};

